name: Daily Data Processing

on:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 3:00 AM US Eastern Time

jobs:
  process_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download data
        run: |
          wget -O data.csv https://fccprod.servicenowservices.com/api/x_g_fmc_rmd/rmd/csv_download

      - name: Process data
        run: |
          # Install necessary tools
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install pandas

          # Process data with Python
          python3 <<EOF
          import pandas as pd

          df = pd.read_csv('data.csv')
          df = df[['business_name', 'contact_telephone_number']]
          df = df.rename(columns={'business_name': 'name', 'contact_telephone_number': 'phoneNumber'})
          df['label'] = 'Telemarketing'
          df['avatar'] = ''
          df['isSubscribed'] = ''
          df['count'] = ''
          df['url'] = ''
          df = df[['phoneNumber', 'label', 'name', 'avatar', 'isSubscribed', 'count', 'url']]
          df.to_csv('processed_data.csv', index=False)
          EOF

      - name: Commit changes
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            if (fs.existsSync('processed_data.csv')) {
              github.rest.repos.createOrUpdateFileContents({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: 'processed_data.csv',
                message: 'Update processed data',
                content: fs.readFileSync('processed_data.csv', 'base64'),
                sha: context.payload.before
              });
            }
