name: US FTC Robocall Daily Data Processing

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  process_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4  # Updated to v4
        with:
          ref: us         # Checkout the 'us' branch
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pandas
        run: pip install pandas


      - name: Download FTC data
        run: |
          year=$(date -d "yesterday" +%Y)
          month=$(date -d "yesterday" +%m)
          day=$(date -d "yesterday" +%d)
          wget -O ftc_data.csv "https://www.ftc.gov/sites/default/files/DNC_Complaint_Numbers_${year}-${month}-${day}.csv"

      - name: Process FTC data
        run: |
          # Install necessary tools
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install pandas

          # Process FTC data with Python
          python3 <<EOF
          import pandas as pd
          import re
          
          df = pd.read_csv('ftc_data.csv')
          df = df[['Company_Phone_Number']]
          df = df.rename(columns={'Company_Phone_Number': 'phoneNumber'})
          
          df['phoneNumber'] = df['phoneNumber'].astype(str).apply(lambda x: re.sub(r"\.0$", "", x))
          df['phoneNumber'] = df['phoneNumber'].str.strip()
          df = df[df['phoneNumber'] != '']
          df.dropna(subset=['phoneNumber'], inplace=True) 


          
          df['label'] = 'Robocall'
          df['name'] = ''
          df['avatar'] = ''
          df['isSubscribed'] = True  # Set isSubscribed to True
          df['count'] = ''
          df['url'] = ''
          df = df[['phoneNumber', 'label', 'name', 'avatar', 'isSubscribed', 'count', 'url']]
          df.to_csv('processed_ftc_data.csv', index=False)
          EOF
      

      - name: Commit and Push CSV
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update processed FTC data"
          file_pattern: "processed_ftc_data.csv"
          branch: us             # Push to the 'us' branch
          repository: .
          token: ${{ secrets.secrets.YOUR_GITHUB_TOKEN }}
