/// Flutter icons NewSet
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NewSet
///      fonts:
///       - asset: fonts/NewSet.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class NewSet {
  NewSet._();

  static const _kFontFam = 'NewSet';
  static const String? _kFontPkg = null;

  static const IconData chat_off = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_off = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_check = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_call = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_forwarded = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_incoming = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_missed = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_off = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_outgoing = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_off = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_z_a = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_0_1 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_1_0 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_delete = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_horiz = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_a_z = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_off = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bubble = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_x = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_archive = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_minus = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_check = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_down = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_pen = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_up = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_add = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apps = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_upload = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_sync = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_off = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_fill = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_download = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_done = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData language = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_forbid = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_check = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_minus = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_plus = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_round_search = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_x = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip_back = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip_forward = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sync_problem = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sync_disabled = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vip = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whitelist = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whitelist_fill = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData voiceprint = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blacklist = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blacklist_fill = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cached = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blocked = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData autorenew = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wildcard = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rewind_start = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward_end = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plugins_1 = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plugins = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData record = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_record = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_off = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_history = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData label = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData allowed = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications_none = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications_off = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fingerprint = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unfold_more = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumb_down = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumb_up = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData create = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_auto = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_rejected = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData color_lens = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sms = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData translate = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_line = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData onedrive = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_quote = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left = IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscription = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp = IconData(0xf232, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telegram = IconData(0xf2c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_drive = IconData(0xf3aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_play = IconData(0xf3ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
